services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: visionboard
      POSTGRES_USER: visionboard
      POSTGRES_PASSWORD: visionboard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U visionboard"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  backend:
    build: ../backend
    ports:
    - "8000:8000"         
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=visionboard_backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=visionboard
      - POSTGRES_USER=visionboard
      - POSTGRES_PASSWORD=visionboard
      - POSTGRES_HOST=postgres
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=visionboard-ai
      - AWS_S3_REGION_NAME=us-east-2   

    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
            gunicorn visionboard_backend.wsgi:application --bind 0.0.0.0:8000"

  worker:
    build: ../worker
    volumes:
      - ../worker:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=visionboard
      - POSTGRES_USER=visionboard
      - POSTGRES_PASSWORD=visionboard
    depends_on:
      - redis
      - postgres
      - backend

  frontend:
    build: ../frontend
    ports: ["4200:4200"]
    depends_on:
      - backend

volumes:
  postgres_data:
